services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      mynetwork:
        ipv4_address: 172.30.0.2
    volumes:
      - ansible_data:/home/ansible

  debian:
    build:
      context: .
      dockerfile: debian.Dockerfile
    container_name: debian
    networks:
      mynetwork:
        ipv4_address: 172.30.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/16"

volumes:
  jenkins_data:
    driver: local
